### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by darkt1981** [garagepoort/staffplusplus-discord#1]
Not sure if im at fault here or not.

Paper MC 1.18.2:

[15:56:03] [Server thread/ERROR]: Error occurred while enabling StaffPlusPlusDiscord v1.16.63 (Is it up to date?)
java.lang.NoClassDefFoundError: net/shortninja/staffplusplus/warnings/WarningCreatedEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at be.garagepoort.staffplusplus.discord.be.garagepoort.mcioc.ReflectionUtils.getMethodsAnnotatedWith(ReflectionUtils.java:21) ~[staffplusplus-discord-1.16.63.jar:?]
	at be.garagepoort.staffplusplus.discord.be.garagepoort.mcioc.IocConditionalFilter.isValidBean(IocConditionalFilter.java:12) ~[staffplusplus-discord-1.16.63.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at be.garagepoort.staffplusplus.discord.be.garagepoort.mcioc.IocContainer.loadIocBeans(IocContainer.java:70) ~[staffplusplus-discord-1.16.63.jar:?]
	at be.garagepoort.staffplusplus.discord.be.garagepoort.mcioc.IocContainer.init(IocContainer.java:46) ~[staffplusplus-discord-1.16.63.jar:?]
	at be.garagepoort.staffplusplus.discord.be.garagepoort.mcioc.TubingPlugin.onEnable(TubingPlugin.java:27) ~[staffplusplus-discord-1.16.63.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-299]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-299]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.shortninja.staffplusplus.warnings.WarningCreatedEvent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 28 more
[15:56:03] [Server thread/INFO]: [StaffPlusPlusDiscord] Disabling StaffPlusPlusDiscord v1.16.63

**Comment by garagepoort** [comment]
Hey @darkt1981 
What version of staff++ are you using?

**Comment by darkt1981** [comment]
Staff++ 1.18.14 latest accoording to the spigot page.

**Comment by garagepoort** [comment]
And are you sure the core plugin is running without issues? Can you share the full server log file?

**Comment by darkt1981** [comment]
If been using staff++ for a few weeks now, i just installed the discord thingy yesterday. When i have time ill send it, could be i made a typo in the config file, maybe?

⁣BlueMail voor Android downloaden ​

Op 7 mei 2022 16:30, om 16:30, David Maes ***@***.***> schreef:
>And are you sure the core plugin is running without issues? Can you
>share the full server log file?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/garagepoort/staffplusplus-discord/issues/1#issuecomment-1120219838
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by darkt1981** [comment]
[latest.log](https://github.com/garagepoort/staffplusplus-discord/files/8651743/latest.log)

Same issue again when doeing a new config file generation.

**Comment by garagepoort** [comment]
Hey @darkt1981 

You are not running staff++

```
:41:11] [Server thread/INFO]: [StaffPlus] Enabling StaffPlus v3.3.10.0
```

You need staff++ and not staff+ to use this plugin.
https://www.spigotmc.org/resources/staff.83562/

**Comment by darkt1981** [comment]
Afff i see whats ging on i had both plugins installed and 1 broke the other xD
thanks.
